Repository ALLREVA/Allreva_FE, pull requests merged in 2024-12, with the labels that each got.

#70 [ARV-85] Input Field 컴포넌트 구현
  package.json
  src/components/buttons/BaseButton.tsx
  src/components/inputField/InputField.stories.tsx
  src/components/inputField/InputField.tsx
  src/components/inputField/TitleInputField.stories.tsx
  src/components/inputField/TitleInputField.tsx
  yarn.lock
Labels: ✨ feature

#76 [ARV-95] Tanstack Query 설정
  package.json
  src/main.tsx
  src/pages/Home.tsx
  yarn.lock
Labels: ⚙️ chore

#68 [ARV-84] onSearch callback prop 추가
  src/components/searchInput/SearchInput.stories.tsx
  src/components/searchInput/SearchInput.tsx
Labels: ✨ feature

#69 [ARV-82] Dialog 컴포넌트 구현
  .storybook/preview.tsx
  src/components/bottomSheet/BottomSheet.stories.tsx
  src/components/bottomSheet/BottomSheet.tsx
  src/components/dialog/Dialog.stories.tsx
  src/components/dialog/Dialog.tsx
  src/components/modalRenderer/ModalRenderer.tsx
  src/constants/ModalTypes.ts
  src/stores/index.ts
  src/stores/useBottomSheetStore.ts
  src/stores/useModalStore.ts
  src/types/.gitkeep
  src/types/index.ts
  src/types/modal.ts
Labels: ✨ feature, ♻️ refactor

#79 [ARV-97] Global Layout 구현
  index.html
  src/App.tsx
  src/components/bottomNav/BottomNav.tsx
  src/components/bottomSheet/BottomSheet.tsx
  src/components/header/Header.tsx
  src/components/subHeader/SubHeader.tsx
  src/components/topNav/TopNav.tsx
  src/layout/FullLayout.tsx
  src/layout/HeaderLayout.tsx
  src/layout/SearchLayout.tsx
  src/layout/TitleHeaderLayout.tsx
  src/layout/index.ts
  src/pages/busRental/BusRental.tsx
  src/pages/busRentalDetail/BusRentalDetail.tsx
  src/pages/concert/Concert.tsx
  src/pages/concertDetail/ConcertDetail.tsx
  src/pages/concertRecord/ConcertRecord.tsx
  src/pages/editProfile/EditProfile.tsx
  src/pages/home/Home.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/myRentalList/MyRentalList.tsx
  src/pages/myRentalManagement/MyRentalManagement.tsx
  src/pages/mySurveyList/MySurveyList.tsx
  src/pages/mySurveyManagement/MySurveyManagement.tsx
  src/pages/openBusRental/OpenBusRental.tsx
  src/pages/openSurvey/OpenSurvey.tsx
  src/pages/signIn/SignIn.tsx
  src/pages/signUp/SignUp.tsx
  src/pages/surveyDetail/SurveyDetail.tsx
  src/pages/surveyDetail/components/.gitkeep
  src/pages/surveys/Surveys.tsx
  src/pages/surveys/components/.gitkeep
  src/routes/routes.tsx
  src/styles/GlobalStyle.tsx
Labels: 🎨 design, ✨ feature

#83 [ARV-110] React Query Devtools main에 추가
  src/main.tsx
Labels: ⚙️ chore

#84 [ARV-103] MyPage 레이아웃 구현
  .gitignore
  index.html
  public/favicon.png
  src/App.tsx
  src/api/index.ts
  src/api/refundAccount.ts
  src/components/.gitkeep
  src/components/badge/Badge.tsx
  src/components/bottomNav/BottomNav.tsx
  src/components/bottomSheet/BottomSheet.tsx
  src/components/buttons/BaseButton.tsx
  src/components/editButton/EditButton.tsx
  src/components/imageField/ImageField.tsx
  src/constants/endPoint.ts
  src/constants/modalType.ts
  src/constants/url.ts
  src/hooks/index.ts
  src/hooks/useScreenSize.ts
  src/layout/FullLayout.tsx
  src/layout/HeaderLayout.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/components/.gitkeep
  src/pages/myPage/components/AccountStatus.tsx
  src/pages/myPage/components/ManagementSection.tsx
  src/pages/myPage/components/RefundBottomSheet.tsx
  src/pages/myPage/components/UserProfile.tsx
  src/schemas/index.ts
  src/schemas/refundAccountSchema.ts
  src/types/index.ts
  src/types/modal.ts
  src/types/user.ts
  src/utils/axios.ts
  src/utils/index.ts
Labels: 🎨 design, ✨ feature

#85 [ARV-109] Concert page layout 구현
  .env
  src/pages/concert/Concert.tsx
Labels: 🎨 design

#87 [ARV-92] 차량 대절 상세 페이지 레이아웃 구현
  src/components/inputField/InputField.tsx
  src/components/subHeader/SubHeader.tsx
  src/constants/FilterTypes.ts
  src/hooks/useRentalDetails.ts
  src/mocks/handlers.ts
  src/pages/busRentalDetail/BusRentalDetail.tsx
  src/pages/busRentalDetail/components/.gitkeep
  src/pages/busRentalDetail/components/BusTime.tsx
  src/pages/busRentalDetail/components/DepositAccount.tsx
  src/pages/busRentalDetail/components/DrivingInfo.tsx
  src/pages/busRentalDetail/components/ParticipantsStatus.tsx
  src/styles/GlobalStyle.tsx
  src/types/api.ts
  src/types/busRental.ts
  src/types/index.ts
  src/utils/dateUtils.ts
Labels: 🎨 design, ✨ feature

#91 [ARV-123] 차량 대절 복사 Toast 추가
  .storybook/preview.tsx
  src/components/toast/Toast.stories.tsx
  src/components/toast/Toast.tsx
  src/components/toast/ToastRenderer.tsx
  src/constants/filterTypes.ts
  src/constants/toastMessage.ts
  src/pages/busRentalDetail/BusRentalDetail.tsx
  src/pages/busRentalDetail/components/DepositAccount.tsx
  src/routes/routes.tsx
  src/stores/index.ts
  src/stores/useToastStore.ts
  src/types/busRental.ts
  src/utils/index.ts
Labels: ✨ feature

#95 [ARV-125] my survey management 레이아웃 구현
  src/api/index.ts
  src/api/refundAccountApi.ts
  src/api/surveyApi.ts
  src/api/surveyFormApi.ts
  src/constants/endPoint.ts
  src/pages/mySurveyManagement/MySurveyManagement.tsx
  src/pages/mySurveyManagement/components/EmptySurvey.tsx
  src/pages/mySurveyManagement/components/SurveyItem.tsx
  src/queries/rent/.gitkeep
  src/queries/rentForm/.gitkeep
  src/queries/survey/index.ts
  src/queries/survey/useCreatedSurveys.ts
  src/queries/surveyForm/.gitkeep
  src/types/index.ts
  src/types/survey.ts
Labels: 🎨 design, ✨ feature, 🧩 style

#97 [ARV-125] ConcertDetail 페이지 구현
  src/components/topNav/TopNav.tsx
  src/constants/endPoint.ts
  src/pages/concert/Concert.tsx
  src/pages/concert/components/ConcertItem.tsx
  src/pages/concertDetail/ConcertDetail.tsx
  src/pages/concertDetail/components/.gitkeep
  src/pages/concertDetail/components/ConcertInfo.tsx
  src/pages/concertDetail/components/IconText.tsx
  src/pages/concertDetail/components/PosterContent.tsx
  src/pages/concertDetail/components/SeatInfo.tsx
  src/pages/concertDetail/type.ts
  src/routes/routes.tsx
Labels: 🎨 design, ✨ feature

#105 [ARV-149] 메인 페이지 구현
  package.json
  src/constants/endPoint.ts
  src/pages/home/Home.tsx
  src/pages/home/components/MainPoster.tsx
  yarn.lock
Labels: 🎨 design, ✨ feature

#110 [ARV-140] 수요 조사 메인 페이지 구현
  src/api/surveyApi.ts
  src/components/bottomSheet/BottomSheet.tsx
  src/pages/surveyDetail/SurveyDetail.tsx
  src/pages/surveys/Surveys.tsx
  src/pages/surveys/components/.gitkeep
  src/pages/surveys/components/SurveyItem.tsx
  src/queries/survey/index.ts
  src/queries/survey/useMyCreatedSurveys.ts
  src/queries/survey/useSurveyList.ts
  src/types/survey.ts
Labels: 🎨 design, ✨ feature

#112 [ARV-153] 1차 배포
  src/components/avatarUploader/AvatarUploader.stories.tsx
  src/components/topNav/TopNav.tsx
  src/pages/busRentalDetail/components/RentalInputField.tsx
  src/pages/editProfile/EditProfile.tsx
  src/pages/myPage/components/RefundBottomSheet.tsx
  src/pages/mySurveyManagement/MySurveyManagement.tsx
  src/pages/mySurveyManagement/components/SurveyItem.tsx
  src/routes/routes.tsx
  src/types/survey.ts
Labels: 🪚 fix, 🚀deploy

#113 [Deploy] Netlify redirects 설정
  public/_redirects
Labels: 🪚 fix, 🚀deploy

#116 [ARV-156] 로그인 인증 개선
  src/constants/endPoint.ts
  src/pages/callback/Callback.tsx
  src/pages/signIn/SignIn.tsx
  src/pages/signUp/SignUp.tsx
  src/routes/routes.tsx
  src/stores/authStore.ts
Labels: ✨ feature, 🪚 fix

#118 [ARV-161] 수요 조사 개설 페이지 레이아웃
  package.json
  src/pages/openSurvey/OpenSurvey.tsx
  src/pages/openSurvey/components/SearchField.tsx
  vite.config.ts
  yarn.lock
Labels: 🎨 design

#121 [ARV-166] 로그인 및 토큰 처리
  src/App.tsx
  src/constants/endPoint.ts
  src/main.tsx
  src/pages/callback/Callback.tsx
  src/stores/authStore.ts
  src/utils/axios.ts
Labels: ✨ feature

#124 [ARV-170] Protected routes 구현
  src/components/header/Header.tsx
  src/layout/ProtectedRoutes.tsx
  src/routes/routes.tsx
Labels: ✨ feature
