Repository ALLREVA/Allreva_FE, pull requests merged in 2025-01, with the labels that each got.

#127 [ARV-169] 수요 조사 개설 구현
  src/components/calendar/Calendar.tsx
  src/components/checkbox/Checkbox.tsx
  src/pages/concert/components/ListItem.tsx
  src/pages/openSurvey/OpenSurvey.tsx
  src/pages/openSurvey/components/.gitkeep
  src/pages/openSurvey/components/CalendarBottomSheet.tsx
  src/pages/openSurvey/components/SelectedConcertItem.tsx
  src/pages/openSurvey/type.ts
  src/utils/dateUtils.ts
Labels: ✨ feature

#128 [ARV-157] 차대절 폼 개설 구현
  package.json
  src/api/index.ts
  src/api/rentalApi.ts
  src/api/rentalFormApi.ts
  src/api/searchApi.ts
  src/assets/images/magnifier-icon.svg
  src/components/buttons/BaseButton.tsx
  src/components/searchInput/SearchInput.tsx
  src/components/tabBar/TabBar.tsx
  src/constants/placeholder.ts
  src/main.tsx
  src/pages/busRental/BusRental.tsx
  src/pages/openBusRental/OpenBusRental.tsx
  src/pages/openBusRental/components/.gitkeep
  src/pages/openBusRental/components/items/CheckboxItem.tsx
  src/pages/openBusRental/components/items/EndDateCalendar.tsx
  src/pages/openBusRental/components/items/RentalFormSelect.tsx
  src/pages/openBusRental/components/items/RentalInputField.tsx
  src/pages/openBusRental/components/items/RentalThumbField.tsx
  src/pages/openBusRental/components/items/RentalTitleField.tsx
  src/pages/openBusRental/components/items/SearchArtistItem.tsx
  src/pages/openBusRental/components/items/SearchConcertItem.tsx
  src/pages/openBusRental/components/items/SearchField.tsx
  src/pages/openBusRental/components/items/TextArea.tsx
  src/pages/openBusRental/components/lists/BoardingDateCheckList.tsx
  src/pages/openBusRental/components/lists/RefundTypeRadio.tsx
  src/pages/openBusRental/components/sections/AdditionalFormInfo.tsx
  src/pages/openBusRental/components/sections/DetailFormInfo.tsx
  src/pages/openBusRental/components/sections/DrivingFormInfo.tsx
  src/pages/openBusRental/components/sections/FormSubmitDialog.tsx
  src/pages/openBusRental/components/sections/RentalFormField.tsx
  src/pages/openBusRental/components/sheets/BusInfoSheet.tsx
  src/pages/openBusRental/components/sheets/EndDateSheet.tsx
  src/pages/openBusRental/components/sheets/RegionListSheet.tsx
  src/pages/openBusRental/components/sheets/SearchArtistSheet.tsx
  src/pages/openBusRental/components/sheets/SearchConcertSheet.tsx
  src/queries/rent/useGetRentList.ts
  src/queries/rent/useGetRentalDetails.ts
  src/queries/rentForm/.gitkeep
  src/queries/rentForm/usePostRentalForm.ts
  src/queries/search/useGetSearchArtist.ts
  src/queries/search/useGetSearchConcert.ts
  src/schemas/index.ts
  src/schemas/rentalFormSchema.ts
  src/stores/index.ts
  src/stores/rentalFormStore.ts
  src/types/index.ts
  src/types/rentalForm.ts
  src/types/search.ts
  src/utils/dateUtils.ts
  src/utils/index.ts
  src/utils/rentalFormUtils.ts
  src/vite-env.d.ts
  vite.config.ts
  yarn.lock
Labels: ✨ feature

#129 [ARV-150] 실시간 검색어 컴포넌트 구현
  src/components/popularKeyword/PopularKeyword.stories.tsx
  src/components/popularKeyword/PopularKeyword.tsx
  src/constants/endPoint.ts
Labels: ✨ feature

#131 [ARV-176] 메인 페이지 구성 요소 추가
  src/pages/home/Home.tsx
  src/pages/home/components/.gitkeep
  src/pages/home/components/MainPoster.tsx
  src/pages/surveys/components/SurveyItem.tsx
  yarn.lock
Labels: ✨ feature

#133 [ARV-174] 차량 대절 상세 수정
  src/api/rentalApi.ts
  src/components/counter/Counter.tsx
  src/constants/placeholder.ts
  src/pages/busRentalDetail/BusRentalDetail.tsx
  src/pages/busRentalDetail/components/DepositFormSheet.tsx
  src/pages/busRentalDetail/components/RentalInputField.tsx
  src/pages/busRentalDetail/components/items/DepositInputField.tsx
  src/pages/busRentalDetail/components/items/RadioItem.tsx
  src/pages/busRentalDetail/components/lists/BoardingDateRadio.tsx
  src/pages/busRentalDetail/components/lists/BoardingTypeRadio.tsx
  src/pages/busRentalDetail/components/lists/RefundTypeRadio.tsx
  src/pages/busRentalDetail/components/sections/BusTime.tsx
  src/pages/busRentalDetail/components/sections/DepositAccount.tsx
  src/pages/busRentalDetail/components/sections/DrivingInfo.tsx
  src/pages/busRentalDetail/components/sections/ParticipantsStatus.tsx
  src/pages/busRentalDetail/components/sheets/DepositDialog.tsx
  src/pages/busRentalDetail/components/sheets/DepositFormSheet.tsx
  src/pages/openBusRental/components/lists/RefundTypeRadio.tsx
  src/pages/openBusRental/components/sections/FormSubmitDialog.tsx
  src/queries/rent/index.ts
  src/queries/rent/useGetRentList.ts
  src/queries/rent/useGetRentalDetails.ts
  src/queries/rent/usePostDepositForm.ts
  src/queries/rentForm/index.ts
  src/schemas/depositFormSchema.ts
  src/types/rental.ts
  src/utils/dateUtils.ts
Labels: ✨ feature, 🪚 fix

#135 [ARV-171] 프로필 수정 기능 구현
  src/api/index.ts
  src/api/refundAccountApi.ts
  src/api/userApi.ts
  src/components/header/Header.tsx
  src/constants/endPoint.ts
  src/pages/editProfile/EditProfile.tsx
  src/pages/editProfile/components/.gitkeep
  src/pages/editProfile/components/ArtistInput.tsx
  src/pages/editProfile/components/EditProfileForm.tsx
  src/pages/editProfile/components/EmailInput.tsx
  src/pages/editProfile/components/IntroduceInput.tsx
  src/pages/editProfile/components/NicknameInput.tsx
  src/pages/editProfile/components/index.ts
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/components/AccountStatus.tsx
  src/pages/myPage/components/RefundBottomSheet.tsx
  src/pages/myPage/components/UserProfile.tsx
  src/queries/user/useGetUserInfo.ts
  src/schemas/index.ts
  src/schemas/refundAccountSchema.ts
  src/schemas/userProfileSchema.ts
  src/types/user.ts
Labels: ✨ feature

#136 [ARV-1791] 컴색 페이지 구현
  src/components/popularKeyword/PopularKeyword.tsx
  src/constants/endPoint.ts
  src/layout/SearchLayout.tsx
  src/pages/home/Home.tsx
  src/pages/openSurvey/OpenSurvey.tsx
  src/pages/search/Search.tsx
  src/pages/search/components/.gitkeep
  src/pages/search/components/RecentSearch.tsx
  src/pages/searchMore/SearchMoreConcerts.tsx
  src/pages/searchMore/SearchMoreRents.tsx
  src/pages/searchMore/SearchMoreSurveys.tsx
  src/pages/searchMore/type.ts
  src/pages/surveys/Surveys.tsx
  src/routes/routes.tsx
  src/types/search.ts
Labels: ✨ feature

#144 [ARV-190] 공연장 상세 레이아웃 구현
  src/components/rating/Rating.stories.tsx
  src/components/rating/Rating.tsx
  src/components/tabBar/TabBar.stories.tsx
  src/pages/concertHallDetail/ConcertHallDetail.tsx
  src/pages/concertHallDetail/components/RelatedConcert.tsx
  src/pages/concertHallDetail/components/SeatReview.tsx
  src/pages/concertHallDetail/components/SeatReviewItem.tsx
  src/pages/concertHallDetail/components/SeatReviewSheet.tsx
  src/routes/routes.tsx
  src/types/concertHall.ts
  src/types/index.ts
  src/utils/dateUtils.ts
Labels: 🎨 design

#146 [ARV-200] 콘서트 홀 메인 페이지 구현
  src/api/concertHalls.ts
  src/components/topNav/TopNav.tsx
  src/constants/endPoint.ts
  src/pages/concertHallsList/ConcertHallsList.tsx
  src/pages/concertHallsList/components/ConcertHallItem.tsx
  src/pages/concertHallsList/components/FilterChips.tsx
  src/pages/concertHallsList/components/ListItem.tsx
  src/pages/concertHallsList/type.ts
  src/routes/routes.tsx
Labels: ✨ feature

#149 [ARV-205] 공연장 상세 페이지 연동
  package.json
  src/api/concertHallApi.ts
  src/api/index.ts
  src/api/rentalApi.ts
  src/components/rating/Rating.tsx
  src/pages/concertHallDetail/ConcertHallDetail.tsx
  src/pages/concertHallDetail/components/ConcertHallMap.tsx
  src/pages/concertHallDetail/components/SeatReviewItem.tsx
  src/queries/concertHall/index.ts
  src/queries/concertHall/useGetConcertHallDetail.ts
  src/types/concertHall.ts
  tsconfig.json
  yarn.lock
Labels: ✨ feature
