Repository ALLREVA/Allreva_FE, pull requests merged in 2025-03, with the labels that each got.

#158 [ARV-218] 공연장 리뷰 기능 구현 및 로그인 기능 수정
  src/App.tsx
  src/api/authApi.ts
  src/api/userApi.ts
  src/assets/Logo.svg
  src/components/avatarUploader/AvatarUploader.tsx
  src/components/bottomNav/BottomNav.tsx
  src/components/boundary/FetchBoundary.tsx
  src/components/boundary/FetchErrorBoundary.tsx
  src/components/boundary/FetchErrorFallback.tsx
  src/components/boundary/index.ts
  src/components/header/Header.tsx
  src/components/searchInput/SearchInput.tsx
  src/components/sheets/SearchConcertSheet.tsx
  src/constants/placeholder.ts
  src/constants/toastMessage.ts
  src/hooks/index.ts
  src/hooks/useLoginCheck.ts
  src/hooks/useUserProfile.ts
  src/layout/FullLayout.tsx
  src/layout/HeaderLayout.tsx
  src/layout/ProtectedRoutes.tsx
  src/layout/TitleHeaderLayout.tsx
  src/pages/busRentalDetail/BusRentalDetail.tsx
  src/pages/callback/Callback.tsx
  src/pages/concert/Concert.tsx
  src/pages/concertHallDetail/ConcertHallDetail.tsx
  src/pages/concertHallsList/components/ConcertHallItem.tsx
  src/pages/createConcertHallReview/CreateConcertHallReview.tsx
  src/pages/createConcertHallReview/components/ConcertDateSelector.tsx
  src/pages/createConcertHallReview/components/ReviewForm.tsx
  src/pages/editProfile/EditProfile.tsx
  src/pages/editProfile/components/EditProfileForm.tsx
  src/pages/editProfile/components/NicknameInput.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/components/RefundBottomSheet.tsx
  src/pages/myPage/utils.ts
  src/pages/signIn/SignIn.tsx
  src/pages/signIn/components/.gitkeep
  src/pages/signIn/components/AnimateLogo.tsx
  src/pages/signIn/components/ShiningButton.tsx
  src/pages/signIn/components/Tagline.tsx
  src/pages/signUp/SignUp.tsx
  src/queries/auth/usePostSignUp.ts
  src/queries/concertHall/useGetConcertHallDetail.ts
  src/queries/rent/useGetRentalDetails.ts
  src/queries/user/useGetUserInfo.ts
  src/queries/user/useRefundAccount.ts
  src/routes/routes.tsx
  src/schemas/seatReviewSchema.ts
  src/schemas/userProfileSchema.ts
  src/stores/authStore.ts
  src/stores/filterStore.ts
  src/stores/toastStore.ts
  src/types/search.ts
  src/types/user.ts
  src/utils/axios.ts
Labels: 🎨 design, ✨ feature, ♻️ refactor

#163 [ARV-230] 로그아웃 기능 추가
  src/api/authApi.ts
  src/components/header/Header.tsx
  src/constants/endPoint.ts
  src/hooks/useLoginCheck.ts
  src/pages/myPage/MyPage.tsx
  src/stores/authStore.ts
Labels: ♻️ refactor

#164 [ARV-228] 회원가입 페이지 아티스트 검색 추가 및 폼 전송 오류 해결
  src/components/items/SearchArtistItem.tsx
  src/components/sheets/SearchArtistSheet.tsx
  src/pages/openBusRental/components/sections/DetailFormInfo.tsx
  src/pages/signUp/SignUp.tsx
  src/pages/signUp/components/.gitkeep
  src/pages/signUp/components/ArtistSelector.tsx
  src/schemas/userProfileSchema.ts
  src/types/search.ts
  src/types/user.ts
Labels: 🪚 fix, ♻️ refactor

#167 [ARV-233] 로그인 유지 오류 수정
  src/components/header/Header.tsx
  src/queries/user/useGetUserInfo.ts
  src/stores/authStore.ts
Labels: 🪚 fix, ♻️ refactor

#168 [ARV-231] 차량 대절 폼에 presigned url 적용
  public/mockServiceWorker.js
  src/api/index.ts
  src/api/rentalApi.ts
  src/api/rentalFormApi.ts
  src/components/bottomNav/BottomNav.tsx
  src/components/inputField/InputField.tsx
  src/components/inputField/TitleInputField.tsx
  src/components/message/ValidationMessage.tsx
  src/components/sheets/SearchConcertSheet.tsx
  src/constants/placeholder.ts
  src/pages/busRentalDetail/components/sheets/DepositFormSheet.tsx
  src/pages/openBusRental/components/items/RentalInputField.tsx
  src/pages/openBusRental/components/items/RentalTextArea.tsx
  src/pages/openBusRental/components/items/RentalThumbField.tsx
  src/pages/openBusRental/components/items/RentalTitleField.tsx
  src/pages/openBusRental/components/modal/FormSubmitDialog.tsx
  src/pages/openBusRental/components/sections/DetailFormInfo.tsx
  src/queries/rentForm/usePostRentalForm.ts
  src/schemas/rentalFormSchema.ts
  src/stores/rentalFormStore.ts
  src/types/rentalForm.ts
  src/utils/rentalFormUtils.ts
  yarn.lock
Labels: ✨ feature, ♻️ refactor
